variables:
- name: BuildParameters.solution
  value: '**\*.sln'
- name: BuildParameters.ArtifactName
  value: drop
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Run on Desktop
  pool:
    name: Default
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: NuGetToolInstaller@0
    displayName: Use NuGet 4.4.1
    inputs:
      versionSpec: 4.4.1
  - task: NuGetToolInstaller@1
    displayName: Use NuGet >=6.1.0
    inputs:
      versionSpec: '>=6.1.0'
  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      solution: $(BuildParameters.solution)
      noCache: true
  - task: VSBuild@1
    displayName: Build solution
    inputs:
      solution: $(BuildParameters.solution)
      msbuildArgs: /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactstagingdirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration) --no-restore
  - task: PublishSymbols@2
    displayName: Publish symbols path
    continueOnError: True
    inputs:
      SearchPattern: '**\bin\**\*.pdb'
      PublishSymbols: false
      SymbolServerType: TeamServices
  - task: CopyFiles@2
    displayName: 'Copy Artifacts'
    inputs:
      Contents: |
        **\bin\**
        **\obj\**
      targetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: $(BuildParameters.ArtifactName)
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
  - task: VSTest@3
    displayName: VsTest - Run Tests
    inputs:
      testAssemblyVer2: >-
        **\Features\*.feature

        **\SpecFlowCalculator.dll

        **\SpecFlowCalculator.Specs.dll

        **\*.SpecFlowCalculator.dll

        **\*.SpecFlowCalculator.Specs.dll

        !**\*TestAdapter.dll

        !**\obj\**
  - task: SpecFlowPlus@0
    displayName: SpecFlow+ build step.
    inputs:
      projectFilePath: SpecFlowCalculator.Specs
      testExecutionJson: $(Build.SourcesDirectory)\SpecFlowCalculator\SpecFlowCalculator.Specs\bin\Debug\net6.0\TestExecution.json
      projectLanguage: en